apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static-site
  template:
    metadata:
      labels:
        app: nginx-static-site
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: site-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Argo CD!</title>
    </head>
    <body>
        <h1>Hello from Argo CD 🚀</h1>
    </body>
    </html>
